version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service_1
      - service_2
    networks:
      - app-network

  service_1:
    build:
      context: ./service_1
    networks:
      - app-network
    healthcheck:                           # Here , I added healthcheck for both of the services.
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 5
      

  service_2:
    build:
      context: ./service_2
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002"]
      interval: 10s
      timeout: 5s
      retries: 5
    

networks:
  app-network:
    driver: bridge
